# Permalinks

# Setup
title: Tania Chacana
description: Tania Chacana – type & graphic design portfolio
url: https://www.taniachacana.com
baseurl: ""

# About/contact
author:
  name: Tania Chacana
  url: https://www.taniachacana.com
  email: tania.chacana@gmail.com

# Build settings
markdown: kramdown

# The default sharing image for sharing any page to social media. If a post has
# a "sharing_image" meta that will be used instead
# Use a relative path from the root of the project!
sharing_image: /assets/sharing_image.png
